---
version: 0.2

env:
  variables:
    EC2_REGION: "eu-west-2"
    TARGET_ENV: "dev"

phases:
  pre_build:
    commands:
      - export BRANCH_NAME="alpha"
      - |
        if [ ${CODEBUILD_INITIATOR} == "${DEV_PIPELINE_NAME}" ]; then
          export BRANCH_NAME="develop"
        fi
      - export VERSION=${BRANCH_NAME}
  build:
    commands:
      - ansible-galaxy install -r ansible/requirements.yml; USER=$(whoami) packer validate ${PACKER_FILE:-packer.json}
      - ansible-galaxy install -r ansible/requirements.yml; PACKER_VERSION=$(packer --version) USER=$(whoami) packer build ${PACKER_FILE:-packer.json}
