---
- hosts: localhost
  vars_files:
    - ./vars/aws.yml
  tasks:
    - name: Create packer role
      community.aws.iam_role:
        name: "{{ role_name }}"
        assume_role_policy_document: "{{ lookup('file','assume.json') }}"
        purge_policies: yes
        tags:
          project: alfresco
          class: packer

    - name: Create iam policy for role
      community.aws.iam_policy:
        iam_type: role
        iam_name: "{{ role_name }}"
        policy_name: "packer_builder_solr_{{ role_name }}"
        state: present
        policy_json: " {{ lookup( 'file', 'policy.json') }}"

    - name: describe a single role
      community.aws.iam_role_info:
        name: "{{ role_name }}"
      register: role

    - name: set iam profile facts
      set_fact:
        profile_name: "{{ role.iam_roles[0].instance_profiles[0].instance_profile_name }}"

    - name: create build.properties
      template:
        src: build.properties.j2
        dest: "{{ playbook_dir }}/../build.properties"

    - name: debug
      debug:
        msg: "{{ profile_name }}"
